### ISSUE TITLE
Using this with MMDVM?

### ISSUE THREAD

**Issue by dg9vh** [sharkrf/srf-ip-conn-srv#1]
Hi,

is it possible to use this server/reflector also with MMDVMHost-systems like MMDVM and DVMEGA?

73 de Kim
DG9VH

**Comment by nonoo** [comment]
Hello,

MMDVMHost does not support the SharkRF IP Connector Protocol, however, it could be added to the MMDVMHost source code.

73s
Norbert HA2NON

**Comment by dg9vh** [comment]
@nonoo Ok... this is a job for another person - not for me, hi.

Maybe you can get in contact with Jonathan to get him implement it :-)

Actually I am running a test-installation (done in really just a few minutes!). You did a good job!
