### ISSUE TITLE
create ability for configuration of client list syslog interval

### ISSUE THREAD

**Issue by MichaelDBrown** [sharkrf/srf-ip-conn-srv#8]
The daemon logs the full client list to syslog every 30 seconds. This is hard coded on line 364 of client.c. I'd like to add a configuration parameter so that this time interval is configurable. I'd suggest something named client-status-syslog-interval and default it to 30 if it is not set in the configuration file. Changes will be required to client.c, config.c, and config.h. 

This is a very low priority request. I'm happy to complete this and submit a pull request if you'd like.

**Comment by nonoo** [comment]
Can you please send a pull request?
